import { Race, Poll, RatingRecord, ForecastProbability } from './types';

export const SEED_RACES: Race[] = [
  {
    id: "2026-SEN-TX",
    cycle: 2026,
    office: "senate",
    state: "Texas",
    seat_class: "Class II",
    incumbent_party: "REP",
    open_seat: false,
    margin_2024: 5.6,
    needed_for_control: true,
    election_date: "2026-11-03",
    candidates: [
      { name: "Ken Paxton", party: "REP", is_incumbent: true },
      { name: "James Talarico", party: "DEM", is_incumbent: false },
    ],
  },
  {
    id: "2026-SEN-MI",
    cycle: 2026,
    office: "senate",
    state: "Michigan",
    seat_class: "Class II",
    incumbent_party: "DEM",
    open_seat: true,
    margin_2024: 0.8,
    needed_for_control: true,
    election_date: "2026-11-03",
    candidates: [
      { name: "Mike Rogers", party: "REP", is_incumbent: false },
      { name: "Abdul El-Sayed", party: "DEM", is_incumbent: false },
    ],
  },
  {
    id: "2026-HOUSE-NC-07",
    cycle: 2026,
    office: "house",
    state: "North Carolina",
    district: "07",
    incumbent_party: "REP",
    open_seat: false,
    margin_2024: 2.1,
    needed_for_control: true,
    election_date: "2026-11-03",
    candidates: [
      { name: "David Rouzer", party: "REP", is_incumbent: true },
      { name: "Marva Robinson", party: "DEM", is_incumbent: false },
    ],
  }
];

// Seed polls for Texas Senate (4 qualifying polls -> generates average)
export const SEED_POLLS: Poll[] = [
  {
    id: "poll-tx-siena-01",
    race_id: "2026-SEN-TX",
    pollster: "Siena College / NYT",
    sponsor: null,
    field_start: "2026-09-08",
    field_end: "2026-09-12",
    published_at: "2026-09-14T10:00:00Z",
    sample_size: 1120,
    population: "LV",
    method: "live_caller",
    margin_of_error: 3.2,
    hyperpartisan: false,
    results: [
      { candidate: "James Talarico", party: "DEM", pct: 48.0 },
      { candidate: "Ken Paxton", party: "REP", pct: 45.5 },
    ],
    source_id: "siena",
    source_url: "https://www.siena.edu/research",
  },
  {
    id: "poll-tx-marist-01",
    race_id: "2026-SEN-TX",
    pollster: "Marist Poll",
    sponsor: null,
    field_start: "2026-09-05",
    field_end: "2026-09-09",
    published_at: "2026-09-11T12:00:00Z",
    sample_size: 980,
    population: "LV",
    method: "live_caller",
    margin_of_error: 3.4,
    hyperpartisan: false,
    results: [
      { candidate: "James Talarico", party: "DEM", pct: 47.5 },
      { candidate: "Ken Paxton", party: "REP", pct: 45.0 },
    ],
    source_id: "marist",
    source_url: "https://maristpoll.marist.edu",
  },
  {
    id: "poll-tx-quinnipiac-01",
    race_id: "2026-SEN-TX",
    pollster: "Quinnipiac University",
    sponsor: null,
    field_start: "2026-09-01",
    field_end: "2026-09-04",
    published_at: "2026-09-06T09:00:00Z",
    sample_size: 1050,
    population: "LV",
    method: "live_caller",
    margin_of_error: 3.1,
    hyperpartisan: false,
    results: [
      { candidate: "James Talarico", party: "DEM", pct: 47.0 },
      { candidate: "Ken Paxton", party: "REP", pct: 44.5 },
    ],
    source_id: "quinnipiac",
    source_url: "https://poll.qu.edu",
  },
  // Deliberate test case for <3 poll rule: North Carolina-07 has only 2 polls!
  {
    id: "poll-nc-01",
    race_id: "2026-HOUSE-NC-07",
    pollster: "East Carolina University",
    sponsor: null,
    field_start: "2026-09-02",
    field_end: "2026-09-05",
    published_at: "2026-09-07T14:00:00Z",
    sample_size: 650,
    population: "LV",
    method: "mixed",
    margin_of_error: 4.1,
    hyperpartisan: false,
    results: [
      { candidate: "David Rouzer", party: "REP", pct: 49.0 },
      { candidate: "Marva Robinson", party: "DEM", pct: 46.0 },
    ],
    source_id: "ecu",
    source_url: "https://surveyresearch.ecu.edu",
  },
  {
    id: "poll-nc-02",
    race_id: "2026-HOUSE-NC-07",
    pollster: "SurveyUSA",
    sponsor: null,
    field_start: "2026-08-28",
    field_end: "2026-08-31",
    published_at: "2026-09-02T10:00:00Z",
    sample_size: 580,
    population: "RV",
    method: "online",
    margin_of_error: 4.5,
    hyperpartisan: false,
    results: [
      { candidate: "David Rouzer", party: "REP", pct: 48.0 },
      { candidate: "Marva Robinson", party: "DEM", pct: 47.0 },
    ],
    source_id: "surveyusa",
    source_url: "https://www.surveyusa.com",
  }
];

export const SEED_RATINGS: RatingRecord[] = [
  {
    id: "rat-cook-tx",
    race_id: "2026-SEN-TX",
    rater: "cook",
    value: "toss_up",
    verbatim_label: "Toss Up",
    rater_date: "2026-09-15",
    previous_value: "lean_r",
    source_url: "https://www.cookpolitical.com/ratings",
  },
  {
    id: "rat-sabato-tx",
    race_id: "2026-SEN-TX",
    rater: "sabato",
    value: "toss_up",
    verbatim_label: "Toss-Up",
    rater_date: "2026-09-12",
    previous_value: "lean_r",
    source_url: "https://centerforpolitics.org/crystalball",
  },
  {
    id: "rat-inside-tx",
    race_id: "2026-SEN-TX",
    rater: "inside_elections",
    value: "lean_r",
    verbatim_label: "Lean Republican",
    rater_date: "2026-09-10",
    previous_value: "likely_r",
    source_url: "https://www.insideelections.com",
  }
];

export const SEED_FORECASTS: ForecastProbability[] = [
  {
    id: "fc-poly-house",
    scope: "chamber",
    source: "Polymarket Prediction Market",
    metric: "win_probability",
    value: 91.0,
    as_of: "2026-09-19T14:30:00Z",
    source_url: "https://polymarket.com/predictions/midterms",
  },
  {
    id: "fc-poly-senate",
    scope: "chamber",
    source: "Polymarket Prediction Market",
    metric: "win_probability",
    value: 61.0,
    as_of: "2026-09-19T14:30:00Z",
    source_url: "https://polymarket.com/predictions/midterms",
  }
];
