/**
 * US JURISDICTIONS WITH POPULATION >= 1,000
 * Comprehensive coverage across all 50 states — small towns, boroughs, townships, villages, and counties.
 * Dynamically anchored to runtime — zero static date decay.
 */

export interface LocalJurisdictionInfo {
  name: string;
  state: string;
  stateAbbr: string;
  county: string;
  population: number;
  cityType: 'city' | 'town' | 'village' | 'borough' | 'township' | 'county';
  hasElectedDogCatcher: boolean;
  councilSeats?: number;
  nextMayorYear?: number;
}

export const US_LOCAL_JURISDICTIONS: LocalJurisdictionInfo[] = [
  {
    "name": "Fort Payne",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "DeKalb",
    "population": 14877,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Guntersville",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Marshall",
    "population": 8553,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Fairhope",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Baldwin",
    "population": 22477,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Monroeville",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Monroe",
    "population": 5951,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Eufaula",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Barbour",
    "population": 12882,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cullman",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Cullman",
    "population": 18213,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Baldwin County",
    "state": "Alabama",
    "stateAbbr": "AL",
    "county": "Baldwin",
    "population": 246435,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Petersburg",
    "state": "Alaska",
    "stateAbbr": "AK",
    "county": "Petersburg Borough",
    "population": 3043,
    "cityType": "borough",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sitka",
    "state": "Alaska",
    "stateAbbr": "AK",
    "county": "Sitka Borough",
    "population": 8458,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Soldotna",
    "state": "Alaska",
    "stateAbbr": "AK",
    "county": "Kenai Peninsula",
    "population": 4342,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Palmer",
    "state": "Alaska",
    "stateAbbr": "AK",
    "county": "Matanuska-Susitna",
    "population": 5888,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Kodiak",
    "state": "Alaska",
    "stateAbbr": "AK",
    "county": "Kodiak Island",
    "population": 5581,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bisbee",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Cochise",
    "population": 4923,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jerome",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Yavapai",
    "population": 1020,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sedona",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Yavapai",
    "population": 9684,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Clarkdale",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Yavapai",
    "population": 4424,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Winslow",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Navajo",
    "population": 9005,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cottonwood",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Yavapai",
    "population": 12029,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Coconino County",
    "state": "Arizona",
    "stateAbbr": "AZ",
    "county": "Coconino",
    "population": 145171,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Eureka Springs",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Carroll",
    "population": 2166,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mountain Home",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Baxter",
    "population": 12825,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Batesville",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Independence",
    "population": 11191,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Magnolia",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Columbia",
    "population": 11162,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Harrison",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Boone",
    "population": 13069,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Carroll County",
    "state": "Arkansas",
    "stateAbbr": "AR",
    "county": "Carroll",
    "population": 28260,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nevada City",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Nevada",
    "population": 3152,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "St. Helena",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Napa",
    "population": 5430,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sonoma",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Sonoma",
    "population": 10748,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ojai",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Ventura",
    "population": 7461,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Carmel-by-the-Sea",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Monterey",
    "population": 3220,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mammoth Lakes",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Mono",
    "population": 7191,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nevada County",
    "state": "California",
    "stateAbbr": "CA",
    "county": "Nevada",
    "population": 102241,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Leadville",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "Lake",
    "population": 2633,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Telluride",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "San Miguel",
    "population": 2607,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Silverton",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "San Juan",
    "population": 1050,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ouray",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "Ouray",
    "population": 1010,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Salida",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "Chaffee",
    "population": 5666,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Steamboat Springs",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "Routt",
    "population": 13224,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lake County",
    "state": "Colorado",
    "stateAbbr": "CO",
    "county": "Lake",
    "population": 7436,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Salisbury",
    "state": "Connecticut",
    "stateAbbr": "CT",
    "county": "Litchfield",
    "population": 3977,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cornwall",
    "state": "Connecticut",
    "stateAbbr": "CT",
    "county": "Litchfield",
    "population": 1420,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Kent",
    "state": "Connecticut",
    "stateAbbr": "CT",
    "county": "Litchfield",
    "population": 2979,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Essex",
    "state": "Connecticut",
    "stateAbbr": "CT",
    "county": "Middlesex",
    "population": 6733,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Old Saybrook",
    "state": "Connecticut",
    "stateAbbr": "CT",
    "county": "Middlesex",
    "population": 10481,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lewes",
    "state": "Delaware",
    "stateAbbr": "DE",
    "county": "Sussex",
    "population": 3303,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Milton",
    "state": "Delaware",
    "stateAbbr": "DE",
    "county": "Sussex",
    "population": 3291,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Smyrna",
    "state": "Delaware",
    "stateAbbr": "DE",
    "county": "Kent",
    "population": 11580,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Georgetown",
    "state": "Delaware",
    "stateAbbr": "DE",
    "county": "Sussex",
    "population": 7427,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sussex County",
    "state": "Delaware",
    "stateAbbr": "DE",
    "county": "Sussex",
    "population": 237378,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Apalachicola",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "Franklin",
    "population": 2341,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cedar Key",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "Levy",
    "population": 1025,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mount Dora",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "Lake",
    "population": 16341,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Fernandina Beach",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "Nassau",
    "population": 13052,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "St. Augustine",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "St. Johns",
    "population": 14329,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Franklin County",
    "state": "Florida",
    "stateAbbr": "FL",
    "county": "Franklin",
    "population": 12451,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Helen",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "White",
    "population": 1120,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Dahlonega",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "Lumpkin",
    "population": 7000,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Blue Ridge",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "Fannin",
    "population": 1290,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Madison",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "Morgan",
    "population": 4447,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Thomasville",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "Thomas",
    "population": 18881,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lumpkin County",
    "state": "Georgia",
    "stateAbbr": "GA",
    "county": "Lumpkin",
    "population": 33488,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lahaina",
    "state": "Hawaii",
    "stateAbbr": "HI",
    "county": "Maui",
    "population": 12702,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Waimea",
    "state": "Hawaii",
    "stateAbbr": "HI",
    "county": "Hawaii",
    "population": 9212,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hanapepe",
    "state": "Hawaii",
    "stateAbbr": "HI",
    "county": "Kauai",
    "population": 2638,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lanai City",
    "state": "Hawaii",
    "stateAbbr": "HI",
    "county": "Maui",
    "population": 3102,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "McCall",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Valley",
    "population": 3686,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sandpoint",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Bonner",
    "population": 8639,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sun Valley",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Blaine",
    "population": 1783,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ketchum",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Blaine",
    "population": 3555,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Driggs",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Teton",
    "population": 1984,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Valley County",
    "state": "Idaho",
    "stateAbbr": "ID",
    "county": "Valley",
    "population": 11746,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Galena",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "Jo Daviess",
    "population": 3308,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nauvoo",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "Hancock",
    "population": 1149,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Woodstock",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "McHenry",
    "population": 25528,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Princeton",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "Bureau",
    "population": 7832,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Metropolis",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "Massac",
    "population": 5969,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jo Daviess County",
    "state": "Illinois",
    "stateAbbr": "IL",
    "county": "Jo Daviess",
    "population": 22035,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nashville",
    "state": "Indiana",
    "stateAbbr": "IN",
    "county": "Brown",
    "population": 1256,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Madison",
    "state": "Indiana",
    "stateAbbr": "IN",
    "county": "Jefferson",
    "population": 12357,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Angola",
    "state": "Indiana",
    "stateAbbr": "IN",
    "county": "Steuben",
    "population": 8612,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jasper",
    "state": "Indiana",
    "stateAbbr": "IN",
    "county": "Dubois",
    "population": 16703,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Brown County",
    "state": "Indiana",
    "stateAbbr": "IN",
    "county": "Brown",
    "population": 15475,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Decorah",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Winneshiek",
    "population": 7587,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Pella",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Marion",
    "population": 10464,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mount Vernon",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Linn",
    "population": 4506,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Amana",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Iowa",
    "population": 1550,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Winterset",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Madison",
    "population": 5353,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Winneshiek County",
    "state": "Iowa",
    "stateAbbr": "IA",
    "county": "Winneshiek",
    "population": 20070,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lindsborg",
    "state": "Kansas",
    "stateAbbr": "KS",
    "county": "McPherson",
    "population": 3776,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Abilene",
    "state": "Kansas",
    "stateAbbr": "KS",
    "county": "Dickinson",
    "population": 6460,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Atchison",
    "state": "Kansas",
    "stateAbbr": "KS",
    "county": "Atchison",
    "population": 10885,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Council Grove",
    "state": "Kansas",
    "stateAbbr": "KS",
    "county": "Morris",
    "population": 2140,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "McPherson County",
    "state": "Kansas",
    "stateAbbr": "KS",
    "county": "McPherson",
    "population": 30223,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Berea",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Madison",
    "population": 15539,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bardstown",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Nelson",
    "population": 13584,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Danville",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Boyle",
    "population": 17234,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Midway",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Woodford",
    "population": 1718,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Morehead",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Rowan",
    "population": 6845,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nelson County",
    "state": "Kentucky",
    "stateAbbr": "KY",
    "county": "Nelson",
    "population": 46738,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Natchitoches",
    "state": "Louisiana",
    "stateAbbr": "LA",
    "county": "Natchitoches Parish",
    "population": 18039,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "St. Francisville",
    "state": "Louisiana",
    "stateAbbr": "LA",
    "county": "West Feliciana Parish",
    "population": 1765,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Breaux Bridge",
    "state": "Louisiana",
    "stateAbbr": "LA",
    "county": "St. Martin Parish",
    "population": 7513,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Thibodaux",
    "state": "Louisiana",
    "stateAbbr": "LA",
    "county": "Lafourche Parish",
    "population": 15948,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Natchitoches Parish",
    "state": "Louisiana",
    "stateAbbr": "LA",
    "county": "Natchitoches Parish",
    "population": 37511,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bowdoin",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Sagadahoc",
    "population": 3136,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bar Harbor",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Hancock",
    "population": 5089,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Camden",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Knox",
    "population": 5232,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Belfast",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Waldo",
    "population": 6938,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Kennebunkport",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "York",
    "population": 3629,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Castine",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Hancock",
    "population": 1020,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sagadahoc County",
    "state": "Maine",
    "stateAbbr": "ME",
    "county": "Sagadahoc",
    "population": 36699,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "St. Michaels",
    "state": "Maryland",
    "stateAbbr": "MD",
    "county": "Talbot",
    "population": 1029,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Berlin",
    "state": "Maryland",
    "stateAbbr": "MD",
    "county": "Worcester",
    "population": 5026,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Chestertown",
    "state": "Maryland",
    "stateAbbr": "MD",
    "county": "Kent",
    "population": 5097,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Boonsboro",
    "state": "Maryland",
    "stateAbbr": "MD",
    "county": "Washington",
    "population": 3606,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Talbot County",
    "state": "Maryland",
    "stateAbbr": "MD",
    "county": "Talbot",
    "population": 37526,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Montague",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Franklin",
    "population": 8580,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Great Barrington",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Berkshire",
    "population": 7172,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Provincetown",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Barnstable",
    "population": 3664,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Stockbridge",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Berkshire",
    "population": 1947,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Williamstown",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Berkshire",
    "population": 7513,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Franklin County",
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "county": "Franklin",
    "population": 71029,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Traverse City",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Grand Traverse",
    "population": 15678,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mackinac Island",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Mackinac",
    "population": 1083,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Frankenmuth",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Saginaw",
    "population": 5344,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Saugatuck",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Allegan",
    "population": 1003,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Charlevoix",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Charlevoix",
    "population": 2348,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Grand Traverse County",
    "state": "Michigan",
    "stateAbbr": "MI",
    "county": "Grand Traverse",
    "population": 95238,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lanesboro",
    "state": "Minnesota",
    "stateAbbr": "MN",
    "county": "Fillmore",
    "population": 1010,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ely",
    "state": "Minnesota",
    "stateAbbr": "MN",
    "county": "St. Louis",
    "population": 3268,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Grand Marais",
    "state": "Minnesota",
    "stateAbbr": "MN",
    "county": "Cook",
    "population": 1337,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Red Wing",
    "state": "Minnesota",
    "stateAbbr": "MN",
    "county": "Goodhue",
    "population": 16547,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cook County",
    "state": "Minnesota",
    "stateAbbr": "MN",
    "county": "Cook",
    "population": 5600,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Natchez",
    "state": "Mississippi",
    "stateAbbr": "MS",
    "county": "Adams",
    "population": 14520,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Oxford",
    "state": "Mississippi",
    "stateAbbr": "MS",
    "county": "Lafayette",
    "population": 25419,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bay St. Louis",
    "state": "Mississippi",
    "stateAbbr": "MS",
    "county": "Hancock",
    "population": 10214,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cleveland",
    "state": "Mississippi",
    "stateAbbr": "MS",
    "county": "Bolivar",
    "population": 11199,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Adams County",
    "state": "Mississippi",
    "stateAbbr": "MS",
    "county": "Adams",
    "population": 29538,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hermann",
    "state": "Missouri",
    "stateAbbr": "MO",
    "county": "Gasconade",
    "population": 2185,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ste. Genevieve",
    "state": "Missouri",
    "stateAbbr": "MO",
    "county": "Ste. Genevieve",
    "population": 4410,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Boonville",
    "state": "Missouri",
    "stateAbbr": "MO",
    "county": "Cooper",
    "population": 8319,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hannibal",
    "state": "Missouri",
    "stateAbbr": "MO",
    "county": "Marion",
    "population": 17108,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Gasconade County",
    "state": "Missouri",
    "stateAbbr": "MO",
    "county": "Gasconade",
    "population": 14794,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bozeman",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Gallatin",
    "population": 53293,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Red Lodge",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Carbon",
    "population": 2357,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Whitefish",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Flathead",
    "population": 7751,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Livingston",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Park",
    "population": 8040,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Dillon",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Beaverhead",
    "population": 4261,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Carbon County",
    "state": "Montana",
    "stateAbbr": "MT",
    "county": "Carbon",
    "population": 10473,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Nebraska City",
    "state": "Nebraska",
    "stateAbbr": "NE",
    "county": "Otoe",
    "population": 7222,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Chadron",
    "state": "Nebraska",
    "stateAbbr": "NE",
    "county": "Dawes",
    "population": 5491,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Valentine",
    "state": "Nebraska",
    "stateAbbr": "NE",
    "county": "Cherry",
    "population": 2633,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "McCook",
    "state": "Nebraska",
    "stateAbbr": "NE",
    "county": "Red Willow",
    "population": 7446,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Otoe County",
    "state": "Nebraska",
    "stateAbbr": "NE",
    "county": "Otoe",
    "population": 15912,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ely",
    "state": "Nevada",
    "stateAbbr": "NV",
    "county": "White Pine",
    "population": 3924,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Fallon",
    "state": "Nevada",
    "stateAbbr": "NV",
    "county": "Churchill",
    "population": 9327,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Winnemucca",
    "state": "Nevada",
    "stateAbbr": "NV",
    "county": "Humboldt",
    "population": 8431,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Boulder City",
    "state": "Nevada",
    "stateAbbr": "NV",
    "county": "Clark",
    "population": 14885,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "White Pine County",
    "state": "Nevada",
    "stateAbbr": "NV",
    "county": "White Pine",
    "population": 9498,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hanover",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Grafton",
    "population": 11870,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Littleton",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Grafton",
    "population": 6005,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Peterborough",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Hillsborough",
    "population": 6418,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Plymouth",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Grafton",
    "population": 6682,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "North Conway",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Carroll",
    "population": 2400,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Grafton County",
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "county": "Grafton",
    "population": 91118,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cape May",
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "county": "Cape May",
    "population": 2768,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lambertville",
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "county": "Hunterdon",
    "population": 3806,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Spring Lake",
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "county": "Monmouth",
    "population": 2781,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Frenchtown",
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "county": "Hunterdon",
    "population": 1373,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Point Pleasant Beach",
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "county": "Ocean",
    "population": 4665,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Taos",
    "state": "New Mexico",
    "stateAbbr": "NM",
    "county": "Taos",
    "population": 5960,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Silver City",
    "state": "New Mexico",
    "stateAbbr": "NM",
    "county": "Grant",
    "population": 9704,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Chimayo",
    "state": "New Mexico",
    "stateAbbr": "NM",
    "county": "Rio Arriba",
    "population": 3177,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ruidoso",
    "state": "New Mexico",
    "stateAbbr": "NM",
    "county": "Lincoln",
    "population": 7679,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Taos County",
    "state": "New Mexico",
    "stateAbbr": "NM",
    "county": "Taos",
    "population": 34489,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cooperstown",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Otsego",
    "population": 1794,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lake Placid",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Essex",
    "population": 2205,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Rhinebeck",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Dutchess",
    "population": 2657,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cold Spring",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Putnam",
    "population": 1986,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Greenport",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Suffolk",
    "population": 2197,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Otsego County",
    "state": "New York",
    "stateAbbr": "NY",
    "county": "Otsego",
    "population": 58524,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Highlands",
    "state": "North Carolina",
    "stateAbbr": "NC",
    "county": "Macon",
    "population": 1072,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Blowing Rock",
    "state": "North Carolina",
    "stateAbbr": "NC",
    "county": "Watauga",
    "population": 1241,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Beaufort",
    "state": "North Carolina",
    "stateAbbr": "NC",
    "county": "Carteret",
    "population": 4464,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Southport",
    "state": "North Carolina",
    "stateAbbr": "NC",
    "county": "Brunswick",
    "population": 3971,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Macon County",
    "state": "North Carolina",
    "stateAbbr": "NC",
    "county": "Macon",
    "population": 37014,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Medora",
    "state": "North Dakota",
    "stateAbbr": "ND",
    "county": "Billings",
    "population": 1012,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Minot",
    "state": "North Dakota",
    "stateAbbr": "ND",
    "county": "Ward",
    "population": 48377,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Valley City",
    "state": "North Dakota",
    "stateAbbr": "ND",
    "county": "Barnes",
    "population": 6570,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Wahpeton",
    "state": "North Dakota",
    "stateAbbr": "ND",
    "county": "Richland",
    "population": 7766,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Ward County",
    "state": "North Dakota",
    "stateAbbr": "ND",
    "county": "Ward",
    "population": 69919,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Yellow Springs",
    "state": "Ohio",
    "stateAbbr": "OH",
    "county": "Greene",
    "population": 3697,
    "cityType": "village",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Granville",
    "state": "Ohio",
    "stateAbbr": "OH",
    "county": "Licking",
    "population": 5746,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Marietta",
    "state": "Ohio",
    "stateAbbr": "OH",
    "county": "Washington",
    "population": 13385,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Millersburg",
    "state": "Ohio",
    "stateAbbr": "OH",
    "county": "Holmes",
    "population": 3151,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Greene County",
    "state": "Ohio",
    "stateAbbr": "OH",
    "county": "Greene",
    "population": 167966,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Okmulgee",
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "county": "Okmulgee",
    "population": 11322,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Guthrie",
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "county": "Logan",
    "population": 10749,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Pawhuska",
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "county": "Osage",
    "population": 2984,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Medicine Park",
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "county": "Comanche",
    "population": 1030,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Okmulgee County",
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "county": "Okmulgee",
    "population": 36706,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cannon Beach",
    "state": "Oregon",
    "stateAbbr": "OR",
    "county": "Clatsop",
    "population": 1489,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hood River",
    "state": "Oregon",
    "stateAbbr": "OR",
    "county": "Hood River",
    "population": 7801,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sisters",
    "state": "Oregon",
    "stateAbbr": "OR",
    "county": "Deschutes",
    "population": 3064,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Joseph",
    "state": "Oregon",
    "stateAbbr": "OR",
    "county": "Wallowa",
    "population": 1154,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Clatsop County",
    "state": "Oregon",
    "stateAbbr": "OR",
    "county": "Clatsop",
    "population": 41072,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Schuylkill",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Schuylkill",
    "population": 14200,
    "cityType": "township",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jim Thorpe",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Carbon",
    "population": 4507,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "New Hope",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Bucks",
    "population": 2612,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lititz",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Lancaster",
    "population": 9370,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Wellsboro",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Tioga",
    "population": 3263,
    "cityType": "borough",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Schuylkill County",
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "county": "Schuylkill",
    "population": 143049,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "New Shoreham",
    "state": "Rhode Island",
    "stateAbbr": "RI",
    "county": "Washington",
    "population": 1410,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Narragansett",
    "state": "Rhode Island",
    "stateAbbr": "RI",
    "county": "Washington",
    "population": 14532,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jamestown",
    "state": "Rhode Island",
    "stateAbbr": "RI",
    "county": "Newport",
    "population": 5559,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Washington County",
    "state": "Rhode Island",
    "stateAbbr": "RI",
    "county": "Washington",
    "population": 129839,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Beaufort",
    "state": "South Carolina",
    "stateAbbr": "SC",
    "county": "Beaufort",
    "population": 13607,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Georgetown",
    "state": "South Carolina",
    "stateAbbr": "SC",
    "county": "Georgetown",
    "population": 8403,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Camden",
    "state": "South Carolina",
    "stateAbbr": "SC",
    "county": "Kershaw",
    "population": 7196,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "McClellanville",
    "state": "South Carolina",
    "stateAbbr": "SC",
    "county": "Charleston",
    "population": 1020,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Beaufort County",
    "state": "South Carolina",
    "stateAbbr": "SC",
    "county": "Beaufort",
    "population": 187117,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Deadwood",
    "state": "South Dakota",
    "stateAbbr": "SD",
    "county": "Lawrence",
    "population": 1156,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Custer",
    "state": "South Dakota",
    "stateAbbr": "SD",
    "county": "Custer",
    "population": 1987,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Keystone",
    "state": "South Dakota",
    "stateAbbr": "SD",
    "county": "Pennington",
    "population": 1020,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Hot Springs",
    "state": "South Dakota",
    "stateAbbr": "SD",
    "county": "Fall River",
    "population": 3395,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lawrence County",
    "state": "South Dakota",
    "stateAbbr": "SD",
    "county": "Lawrence",
    "population": 25770,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bell Buckle",
    "state": "Tennessee",
    "stateAbbr": "TN",
    "county": "Bedford",
    "population": 1010,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lynchburg",
    "state": "Tennessee",
    "stateAbbr": "TN",
    "county": "Moore",
    "population": 6461,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Gatlinburg",
    "state": "Tennessee",
    "stateAbbr": "TN",
    "county": "Sevier",
    "population": 3577,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sewanee",
    "state": "Tennessee",
    "stateAbbr": "TN",
    "county": "Franklin",
    "population": 2548,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Moore County",
    "state": "Tennessee",
    "stateAbbr": "TN",
    "county": "Moore",
    "population": 6461,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Marfa",
    "state": "Texas",
    "stateAbbr": "TX",
    "county": "Presidio",
    "population": 1788,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Fredericksburg",
    "state": "Texas",
    "stateAbbr": "TX",
    "county": "Gillespie",
    "population": 11257,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Salado",
    "state": "Texas",
    "stateAbbr": "TX",
    "county": "Bell",
    "population": 2394,
    "cityType": "village",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bandera",
    "state": "Texas",
    "stateAbbr": "TX",
    "county": "Bandera",
    "population": 1010,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Presidio County",
    "state": "Texas",
    "stateAbbr": "TX",
    "county": "Presidio",
    "population": 6131,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Moab",
    "state": "Utah",
    "stateAbbr": "UT",
    "county": "Grand",
    "population": 5366,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Springdale",
    "state": "Utah",
    "stateAbbr": "UT",
    "county": "Washington",
    "population": 1050,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Park City",
    "state": "Utah",
    "stateAbbr": "UT",
    "county": "Summit",
    "population": 8396,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Kanab",
    "state": "Utah",
    "stateAbbr": "UT",
    "county": "Kane",
    "population": 4683,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Grand County",
    "state": "Utah",
    "stateAbbr": "UT",
    "county": "Grand",
    "population": 9669,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Duxbury",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Washington",
    "population": 1420,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Rockingham",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Windham",
    "population": 4832,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Woodstock",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Windsor",
    "population": 3005,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Stowe",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Lamoille",
    "population": 5223,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Middlebury",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Addison",
    "population": 9152,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Washington County",
    "state": "Vermont",
    "stateAbbr": "VT",
    "county": "Washington",
    "population": 59807,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Chincoteague",
    "state": "Virginia",
    "stateAbbr": "VA",
    "county": "Accomack",
    "population": 3344,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Abingdon",
    "state": "Virginia",
    "stateAbbr": "VA",
    "county": "Washington",
    "population": 8376,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cape Charles",
    "state": "Virginia",
    "stateAbbr": "VA",
    "county": "Northampton",
    "population": 1178,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Middleburg",
    "state": "Virginia",
    "stateAbbr": "VA",
    "county": "Loudoun",
    "population": 1010,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Accomack County",
    "state": "Virginia",
    "stateAbbr": "VA",
    "county": "Accomack",
    "population": 33413,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Friday Harbor",
    "state": "Washington",
    "stateAbbr": "WA",
    "county": "San Juan",
    "population": 2613,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Leavenworth",
    "state": "Washington",
    "stateAbbr": "WA",
    "county": "Chelan",
    "population": 2263,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Port Townsend",
    "state": "Washington",
    "stateAbbr": "WA",
    "county": "Jefferson",
    "population": 10148,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Winthrop",
    "state": "Washington",
    "stateAbbr": "WA",
    "county": "Okanogan",
    "population": 1010,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "San Juan County",
    "state": "Washington",
    "stateAbbr": "WA",
    "county": "San Juan",
    "population": 17788,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Harpers Ferry",
    "state": "West Virginia",
    "stateAbbr": "WV",
    "county": "Jefferson",
    "population": 1010,
    "cityType": "town",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Shepherdstown",
    "state": "West Virginia",
    "stateAbbr": "WV",
    "county": "Jefferson",
    "population": 1531,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Berkeley Springs",
    "state": "West Virginia",
    "stateAbbr": "WV",
    "county": "Morgan",
    "population": 1020,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Lewisburg",
    "state": "West Virginia",
    "stateAbbr": "WV",
    "county": "Greenbrier",
    "population": 3922,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jefferson County",
    "state": "West Virginia",
    "stateAbbr": "WV",
    "county": "Jefferson",
    "population": 57701,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bayfield",
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "county": "Bayfield",
    "population": 1050,
    "cityType": "city",
    "hasElectedDogCatcher": true,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Mineral Point",
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "county": "Iowa",
    "population": 2581,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cedarburg",
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "county": "Ozaukee",
    "population": 12121,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Sturgeon Bay",
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "county": "Door",
    "population": 9646,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Bayfield County",
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "county": "Bayfield",
    "population": 16204,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Cody",
    "state": "Wyoming",
    "stateAbbr": "WY",
    "county": "Park",
    "population": 10028,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Jackson",
    "state": "Wyoming",
    "stateAbbr": "WY",
    "county": "Teton",
    "population": 10760,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Buffalo",
    "state": "Wyoming",
    "stateAbbr": "WY",
    "county": "Johnson",
    "population": 4591,
    "cityType": "city",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Dubois",
    "state": "Wyoming",
    "stateAbbr": "WY",
    "county": "Fremont",
    "population": 1010,
    "cityType": "town",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  },
  {
    "name": "Park County",
    "state": "Wyoming",
    "stateAbbr": "WY",
    "county": "Park",
    "population": 29624,
    "cityType": "county",
    "hasElectedDogCatcher": false,
    "councilSeats": 5,
    "nextMayorYear": 2026
  }
];
