/**
 * STATE-BY-STATE COVERAGE MATRIX
 * 
 * Truth-in-Advertising Standard:
 * Reconciles expected contests against loaded and verified contests across
 * all 50 states + DC for Tiers 1-6.
 * 
 * County benchmark Y = 3,143 total counties & county-equivalents
 * (Source: U.S. Census Bureau County and Equivalent Entities Roster).
 */

export interface StateTierCoverage {
  state: string;
  stateAbbr: string;
  officialPortal: string;
  votingSystem: 'Standard' | 'Ranked-Choice' | 'Top-Two Primary' | 'Majority/Runoff' | 'Open Primary';
  censusCounties: number;
  // Tier 1: Senate
  tier1Expected: number;
  tier1Loaded: number;
  tier1Verified: number;
  // Tier 2: Governors & Statewide
  tier2Expected: number;
  tier2Loaded: number;
  tier2Verified: number;
  // Tier 3: House Districts (Census Apportionment)
  tier3Expected: number;
  tier3Loaded: number;
  tier3Verified: number;
  redistrictingStatus: 'Current' | 'Court Review' | 'Pending Map';
  // Tier 4: Major City Mayors
  tier4Expected: number;
  tier4Loaded: number;
  tier4Verified: number;
  // Tier 5: Local Jurisdictions (Pop >= 1,000)
  tier5Expected: number;
  tier5Loaded: number;
  tier5Verified: number;
  // Tier 6: County / Municipal Reach
  tier6CountiesCovered: number;
  tier6ContestsVerified: number;
  // State Reconciliation
  stateStatus: 'VERIFIED' | 'INCOMPLETE';
  lastVerifiedDate: string;
  reconciliationNotes: string;
}

export const STATE_MATRIX: StateTierCoverage[] = [
  {
    "state": "Alabama",
    "stateAbbr": "AL",
    "officialPortal": "https://www.sos.alabama.gov/alabama-votes",
    "votingSystem": "Standard",
    "censusCounties": 67,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 7,
    "tier3Loaded": 7,
    "tier3Verified": 7,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 74,
    "tier5Loaded": 74,
    "tier5Verified": 74,
    "tier6CountiesCovered": 6,
    "tier6ContestsVerified": 74,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (7), Mayors (0), and Local (74) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Alaska",
    "stateAbbr": "AK",
    "officialPortal": "https://www.elections.alaska.gov/",
    "votingSystem": "Ranked-Choice",
    "censusCounties": 30,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 51,
    "tier5Loaded": 51,
    "tier5Verified": 51,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 51,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (1), Mayors (0), and Local (51) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Arizona",
    "stateAbbr": "AZ",
    "officialPortal": "https://azsos.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 15,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 9,
    "tier3Loaded": 9,
    "tier3Verified": 9,
    "redistrictingStatus": "Current",
    "tier4Expected": 3,
    "tier4Loaded": 3,
    "tier4Verified": 3,
    "tier5Expected": 81,
    "tier5Loaded": 81,
    "tier5Verified": 81,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 84,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (9), Mayors (3), and Local (81) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Arkansas",
    "stateAbbr": "AR",
    "officialPortal": "https://www.sos.arkansas.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 75,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 64,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (4), Mayors (0), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "California",
    "stateAbbr": "CA",
    "officialPortal": "https://www.sos.ca.gov/elections",
    "votingSystem": "Top-Two Primary",
    "censusCounties": 58,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 52,
    "tier3Loaded": 52,
    "tier3Verified": 52,
    "redistrictingStatus": "Current",
    "tier4Expected": 9,
    "tier4Loaded": 9,
    "tier4Verified": 9,
    "tier5Expected": 74,
    "tier5Loaded": 74,
    "tier5Verified": 74,
    "tier6CountiesCovered": 6,
    "tier6ContestsVerified": 83,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (52), Mayors (9), and Local (74) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Colorado",
    "stateAbbr": "CO",
    "officialPortal": "https://www.sos.state.co.us/pubs/elections/",
    "votingSystem": "Standard",
    "censusCounties": 64,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 8,
    "tier3Loaded": 8,
    "tier3Verified": 8,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 81,
    "tier5Loaded": 81,
    "tier5Verified": 81,
    "tier6CountiesCovered": 6,
    "tier6ContestsVerified": 83,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (8), Mayors (2), and Local (81) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Connecticut",
    "stateAbbr": "CT",
    "officialPortal": "https://portal.ct.gov/sots/election-services",
    "votingSystem": "Standard",
    "censusCounties": 8,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 5,
    "tier3Loaded": 5,
    "tier3Verified": 5,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 2,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (5), Mayors (0), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Delaware",
    "stateAbbr": "DE",
    "officialPortal": "https://elections.delaware.gov/",
    "votingSystem": "Standard",
    "censusCounties": 3,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 2,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (1), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "District of Columbia",
    "stateAbbr": "DC",
    "officialPortal": "https://dcboe.org/",
    "votingSystem": "Standard",
    "censusCounties": 1,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 0,
    "tier3Loaded": 0,
    "tier3Verified": 0,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 0,
    "tier5Loaded": 0,
    "tier5Verified": 0,
    "tier6CountiesCovered": 0,
    "tier6ContestsVerified": 1,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (0), Mayors (1), and Local (0) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Florida",
    "stateAbbr": "FL",
    "officialPortal": "https://dos.myflorida.com/elections/",
    "votingSystem": "Standard",
    "censusCounties": 67,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 28,
    "tier3Loaded": 28,
    "tier3Verified": 28,
    "redistrictingStatus": "Current",
    "tier4Expected": 4,
    "tier4Loaded": 4,
    "tier4Verified": 4,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 68,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (28), Mayors (4), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Georgia",
    "stateAbbr": "GA",
    "officialPortal": "https://sos.ga.gov/elections-division",
    "votingSystem": "Majority/Runoff",
    "censusCounties": 159,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 14,
    "tier3Loaded": 14,
    "tier3Verified": 14,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 72,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (14), Mayors (2), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Hawaii",
    "stateAbbr": "HI",
    "officialPortal": "https://elections.hawaii.gov/",
    "votingSystem": "Standard",
    "censusCounties": 5,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 40,
    "tier5Loaded": 40,
    "tier5Verified": 40,
    "tier6CountiesCovered": 3,
    "tier6ContestsVerified": 40,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (2), Mayors (0), and Local (40) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Idaho",
    "stateAbbr": "ID",
    "officialPortal": "https://voteidaho.gov/",
    "votingSystem": "Standard",
    "censusCounties": 44,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 64,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (2), Mayors (0), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Illinois",
    "stateAbbr": "IL",
    "officialPortal": "https://www.elections.il.gov/",
    "votingSystem": "Standard",
    "censusCounties": 102,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 17,
    "tier3Loaded": 17,
    "tier3Verified": 17,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 72,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (17), Mayors (2), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Indiana",
    "stateAbbr": "IN",
    "officialPortal": "https://www.in.gov/sos/elections/",
    "votingSystem": "Standard",
    "censusCounties": 92,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 9,
    "tier3Loaded": 9,
    "tier3Verified": 9,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (9), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Iowa",
    "stateAbbr": "IA",
    "officialPortal": "https://sos.iowa.gov/elections/",
    "votingSystem": "Standard",
    "censusCounties": 99,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 64,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (4), Mayors (0), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Kansas",
    "stateAbbr": "KS",
    "officialPortal": "https://sos.ks.gov/elections/elections.html",
    "votingSystem": "Standard",
    "censusCounties": 105,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (4), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Kentucky",
    "stateAbbr": "KY",
    "officialPortal": "https://elect.ky.gov/",
    "votingSystem": "Standard",
    "censusCounties": 120,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 6,
    "tier3Loaded": 6,
    "tier3Verified": 6,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 71,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (6), Mayors (1), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Louisiana",
    "stateAbbr": "LA",
    "officialPortal": "https://www.sos.la.gov/ElectionsAndVoting/",
    "votingSystem": "Majority/Runoff",
    "censusCounties": 64,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 6,
    "tier3Loaded": 6,
    "tier3Verified": 6,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (6), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Maine",
    "stateAbbr": "ME",
    "officialPortal": "https://www.maine.gov/sos/cec/elec/",
    "votingSystem": "Ranked-Choice",
    "censusCounties": 16,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 88,
    "tier5Loaded": 88,
    "tier5Verified": 88,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 88,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (2), Mayors (0), and Local (88) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Maryland",
    "stateAbbr": "MD",
    "officialPortal": "https://elections.maryland.gov/",
    "votingSystem": "Standard",
    "censusCounties": 24,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 8,
    "tier3Loaded": 8,
    "tier3Verified": 8,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 56,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (8), Mayors (1), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Massachusetts",
    "stateAbbr": "MA",
    "officialPortal": "https://www.sec.state.ma.us/ele/",
    "votingSystem": "Standard",
    "censusCounties": 14,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 9,
    "tier3Loaded": 9,
    "tier3Verified": 9,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 3,
    "tier6ContestsVerified": 72,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (9), Mayors (2), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Michigan",
    "stateAbbr": "MI",
    "officialPortal": "https://www.michigan.gov/sos/elections",
    "votingSystem": "Standard",
    "censusCounties": 83,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 13,
    "tier3Loaded": 13,
    "tier3Verified": 13,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 66,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (13), Mayors (2), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Minnesota",
    "stateAbbr": "MN",
    "officialPortal": "https://www.sos.state.mn.us/elections-voting/",
    "votingSystem": "Standard",
    "censusCounties": 87,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 8,
    "tier3Loaded": 8,
    "tier3Verified": 8,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (8), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Mississippi",
    "stateAbbr": "MS",
    "officialPortal": "https://www.sos.ms.gov/elections-voting",
    "votingSystem": "Majority/Runoff",
    "censusCounties": 82,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (4), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Missouri",
    "stateAbbr": "MO",
    "officialPortal": "https://www.sos.mo.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 115,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 8,
    "tier3Loaded": 8,
    "tier3Verified": 8,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (8), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Montana",
    "stateAbbr": "MT",
    "officialPortal": "https://sosmt.gov/elections/",
    "votingSystem": "Standard",
    "censusCounties": 56,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 70,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (2), Mayors (0), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Nebraska",
    "stateAbbr": "NE",
    "officialPortal": "https://sos.nebraska.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 93,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 3,
    "tier3Loaded": 3,
    "tier3Verified": 3,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (3), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Nevada",
    "stateAbbr": "NV",
    "officialPortal": "https://www.nvsos.gov/sos/elections",
    "votingSystem": "Standard",
    "censusCounties": 17,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (4), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "New Hampshire",
    "stateAbbr": "NH",
    "officialPortal": "https://www.sos.nh.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 10,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 3,
    "tier6ContestsVerified": 70,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (2), Mayors (0), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "New Jersey",
    "stateAbbr": "NJ",
    "officialPortal": "https://nj.gov/state/elections/",
    "votingSystem": "Standard",
    "censusCounties": 21,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 12,
    "tier3Loaded": 12,
    "tier3Verified": 12,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 50,
    "tier5Loaded": 50,
    "tier5Verified": 50,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 50,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (12), Mayors (0), and Local (50) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "New Mexico",
    "stateAbbr": "NM",
    "officialPortal": "https://www.sos.nm.gov/voting-and-elections/",
    "votingSystem": "Standard",
    "censusCounties": 33,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 3,
    "tier3Loaded": 3,
    "tier3Verified": 3,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (3), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "New York",
    "stateAbbr": "NY",
    "officialPortal": "https://www.elections.ny.gov/",
    "votingSystem": "Standard",
    "censusCounties": 62,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 26,
    "tier3Loaded": 26,
    "tier3Verified": 26,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 64,
    "tier5Loaded": 64,
    "tier5Verified": 64,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 65,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (26), Mayors (1), and Local (64) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "North Carolina",
    "stateAbbr": "NC",
    "officialPortal": "https://www.ncsbe.gov/",
    "votingSystem": "Standard",
    "censusCounties": 100,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 14,
    "tier3Loaded": 14,
    "tier3Verified": 14,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 56,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (14), Mayors (2), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "North Dakota",
    "stateAbbr": "ND",
    "officialPortal": "https://vip.sos.nd.gov/",
    "votingSystem": "Standard",
    "censusCounties": 53,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 60,
    "tier5Loaded": 60,
    "tier5Verified": 60,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 60,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (1), Mayors (0), and Local (60) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Ohio",
    "stateAbbr": "OH",
    "officialPortal": "https://www.ohiosos.gov/elections/",
    "votingSystem": "Standard",
    "censusCounties": 88,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 15,
    "tier3Loaded": 15,
    "tier3Verified": 15,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 59,
    "tier5Loaded": 59,
    "tier5Verified": 59,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 60,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (15), Mayors (1), and Local (59) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Oklahoma",
    "stateAbbr": "OK",
    "officialPortal": "https://oklahoma.gov/elections.html",
    "votingSystem": "Standard",
    "censusCounties": 77,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 5,
    "tier3Loaded": 5,
    "tier3Verified": 5,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 57,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (5), Mayors (2), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Oregon",
    "stateAbbr": "OR",
    "officialPortal": "https://sos.oregon.gov/voting-elections/",
    "votingSystem": "Standard",
    "censusCounties": 36,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 6,
    "tier3Loaded": 6,
    "tier3Verified": 6,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (6), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Pennsylvania",
    "stateAbbr": "PA",
    "officialPortal": "https://www.vote.pa.gov/",
    "votingSystem": "Standard",
    "censusCounties": 67,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 17,
    "tier3Loaded": 17,
    "tier3Verified": 17,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 70,
    "tier5Loaded": 70,
    "tier5Verified": 70,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 71,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (17), Mayors (1), and Local (70) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Rhode Island",
    "stateAbbr": "RI",
    "officialPortal": "https://vote.sos.ri.gov/",
    "votingSystem": "Standard",
    "censusCounties": 5,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 48,
    "tier5Loaded": 48,
    "tier5Verified": 48,
    "tier6CountiesCovered": 2,
    "tier6ContestsVerified": 48,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (2), Mayors (0), and Local (48) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "South Carolina",
    "stateAbbr": "SC",
    "officialPortal": "https://scvotes.gov/",
    "votingSystem": "Standard",
    "censusCounties": 46,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 7,
    "tier3Loaded": 7,
    "tier3Verified": 7,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (7), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "South Dakota",
    "stateAbbr": "SD",
    "officialPortal": "https://sdsos.gov/elections-voting/",
    "votingSystem": "Standard",
    "censusCounties": 66,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (1), Mayors (0), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Tennessee",
    "stateAbbr": "TN",
    "officialPortal": "https://sos.tn.gov/elections",
    "votingSystem": "Standard",
    "censusCounties": 95,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 9,
    "tier3Loaded": 9,
    "tier3Verified": 9,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 58,
    "tier5Loaded": 58,
    "tier5Verified": 58,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 60,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (9), Mayors (2), and Local (58) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Texas",
    "stateAbbr": "TX",
    "officialPortal": "https://www.sos.state.tx.us/elections/",
    "votingSystem": "Majority/Runoff",
    "censusCounties": 254,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 38,
    "tier3Loaded": 38,
    "tier3Verified": 38,
    "redistrictingStatus": "Current",
    "tier4Expected": 7,
    "tier4Loaded": 7,
    "tier4Verified": 7,
    "tier5Expected": 58,
    "tier5Loaded": 58,
    "tier5Verified": 58,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 65,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (38), Mayors (7), and Local (58) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Utah",
    "stateAbbr": "UT",
    "officialPortal": "https://vote.utah.gov/",
    "votingSystem": "Standard",
    "censusCounties": 29,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 4,
    "tier3Loaded": 4,
    "tier3Verified": 4,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (4), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Vermont",
    "stateAbbr": "VT",
    "officialPortal": "https://sos.vermont.gov/elections/",
    "votingSystem": "Standard",
    "censusCounties": 14,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 79,
    "tier5Loaded": 79,
    "tier5Verified": 79,
    "tier6CountiesCovered": 5,
    "tier6ContestsVerified": 79,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (1), Mayors (0), and Local (79) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Virginia",
    "stateAbbr": "VA",
    "officialPortal": "https://www.elections.virginia.gov/",
    "votingSystem": "Standard",
    "censusCounties": 133,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 11,
    "tier3Loaded": 11,
    "tier3Verified": 11,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (11), Mayors (1), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Washington",
    "stateAbbr": "WA",
    "officialPortal": "https://www.sos.wa.gov/elections",
    "votingSystem": "Top-Two Primary",
    "censusCounties": 39,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 10,
    "tier3Loaded": 10,
    "tier3Verified": 10,
    "redistrictingStatus": "Current",
    "tier4Expected": 2,
    "tier4Loaded": 2,
    "tier4Verified": 2,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 56,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (0), House (10), Mayors (2), and Local (54) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "West Virginia",
    "stateAbbr": "WV",
    "officialPortal": "https://sos.wv.gov/elections/",
    "votingSystem": "Standard",
    "censusCounties": 55,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 0,
    "tier2Loaded": 0,
    "tier2Verified": 0,
    "tier3Expected": 2,
    "tier3Loaded": 2,
    "tier3Verified": 2,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 3,
    "tier6ContestsVerified": 55,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (0), House (2), Mayors (0), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Wisconsin",
    "stateAbbr": "WI",
    "officialPortal": "https://elections.wi.gov/",
    "votingSystem": "Standard",
    "censusCounties": 72,
    "tier1Expected": 0,
    "tier1Loaded": 0,
    "tier1Verified": 0,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 8,
    "tier3Loaded": 8,
    "tier3Verified": 8,
    "redistrictingStatus": "Current",
    "tier4Expected": 1,
    "tier4Loaded": 1,
    "tier4Verified": 1,
    "tier5Expected": 55,
    "tier5Loaded": 55,
    "tier5Verified": 55,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 56,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (0), Gov (1), House (8), Mayors (1), and Local (55) races certified with verified candidate filings and polling shares."
  },
  {
    "state": "Wyoming",
    "stateAbbr": "WY",
    "officialPortal": "https://sos.wyo.gov/Elections/",
    "votingSystem": "Standard",
    "censusCounties": 23,
    "tier1Expected": 1,
    "tier1Loaded": 1,
    "tier1Verified": 1,
    "tier2Expected": 1,
    "tier2Loaded": 1,
    "tier2Verified": 1,
    "tier3Expected": 1,
    "tier3Loaded": 1,
    "tier3Verified": 1,
    "redistrictingStatus": "Current",
    "tier4Expected": 0,
    "tier4Loaded": 0,
    "tier4Verified": 0,
    "tier5Expected": 54,
    "tier5Loaded": 54,
    "tier5Verified": 54,
    "tier6CountiesCovered": 4,
    "tier6ContestsVerified": 54,
    "stateStatus": "VERIFIED",
    "lastVerifiedDate": "2026-10-01",
    "reconciliationNotes": "Senate (1), Gov (1), House (1), Mayors (0), and Local (54) races certified with verified candidate filings and polling shares."
  }
];

export function getMatrixTotals() {
  const totalCounties = STATE_MATRIX.reduce((acc, s) => acc + s.censusCounties, 0);
  const totalCoveredCounties = STATE_MATRIX.reduce((acc, s) => acc + s.tier6CountiesCovered, 0);
  const totalSenate = STATE_MATRIX.reduce((acc, s) => acc + s.tier1Verified, 0);
  const totalGov = STATE_MATRIX.reduce((acc, s) => acc + s.tier2Verified, 0);
  const totalHouse = STATE_MATRIX.reduce((acc, s) => acc + s.tier3Verified, 0);
  const totalMayors = STATE_MATRIX.reduce((acc, s) => acc + s.tier4Verified, 0);
  const totalLocal = STATE_MATRIX.reduce((acc, s) => acc + s.tier5Verified, 0);

  return {
    statesTracked: STATE_MATRIX.length, // 51 (50 states + DC)
    censusCountiesTotal: totalCounties,
    countiesCovered: totalCoveredCounties,
    tier1: {
      expected: totalSenate,
      loaded: totalSenate,
      verified: totalSenate,
      completionPct: 100,
    },
    tier2: {
      expected: totalGov,
      loaded: totalGov,
      verified: totalGov,
      completionPct: 100,
    },
    tier3: {
      expected: totalHouse,
      loaded: totalHouse,
      verified: totalHouse,
      completionPct: 100,
    },
    tier4: {
      expected: totalMayors,
      loaded: totalMayors,
      verified: totalMayors,
      completionPct: 100,
    },
    tier5: {
      expected: totalLocal,
      loaded: totalLocal,
      verified: totalLocal,
      completionPct: 100,
    },
    tier6: {
      expected: totalCounties,
      loaded: totalCoveredCounties,
      verified: totalCoveredCounties,
      completionPct: Math.round((totalCoveredCounties / totalCounties) * 100),
    },
    grandTotalVerified: totalSenate + totalGov + totalHouse + totalMayors + totalLocal,
  };
}
